export const sponsors = [
  "/logos/LogoSponsor.webp",
  "/logos/Cup1.webp",
  "/logos/Cup2.webp",
  "/logos/Cup3.webp",
  "/logos/Cup4.webp",
  "/logos/Cup5.webp",
  "/logos/Cup6.webp",
  "/logos/Cup7.webp",
  "/logos/Cup8.webp",
  "/logos/Cup9.webp",
  "/logos/Cup10.webp",
  "/logos/Cup11.webp",
  "/logos/Cup12.webp",
  "/logos/Cup13.webp",
];
