export { SideBar } from "./SideBar";
export { TableProduct } from "@components/dashboard/products/TableProduct";
export { FormProduct } from "@components/dashboard/products/FormProduct";
export { TableDeliverys } from "@components/dashboard/deliverys/TableDeliverys";
export { TablePromo } from "@components/dashboard/promo/TablePromo";
export { FormPromo } from "@components/dashboard/promo/FormPromo";
export { TableCategory } from "@components/dashboard/category/TableCategory";
export { FormCategories } from "@components/dashboard/category/FormCategories";
export { TableOrders } from "@components/dashboard/orders/TableOrders";